<?php

/**
 * Default keyboard actions for the whole application.
 * New screens register here, or through ShortcutRegistry::extend().
 * Do not add a separate keydown listener in a module.
 */
return [
    'shortcuts' => [
        ['id' => 'search', 'keys' => 'Ctrl+K', 'label' => 'Search the menu and companies', 'group' => 'General', 'action' => 'search', 'scope' => 'global', 'when' => 'always'],
        ['id' => 'data-search', 'keys' => 'Alt+F', 'label' => 'Find masters and transactions', 'group' => 'General', 'action' => 'search', 'scope' => 'global', 'when' => 'always'],
        ['id' => 'search-slash', 'keys' => '/', 'label' => 'Search the menu and companies', 'group' => 'General', 'action' => 'search', 'scope' => 'global', 'when' => 'typing-safe'],
        ['id' => 'help', 'keys' => '?', 'label' => 'Show keyboard shortcuts', 'group' => 'General', 'action' => 'help', 'scope' => 'global', 'when' => 'typing-safe'],
        ['id' => 'help-f1', 'keys' => 'F1', 'label' => 'Help', 'group' => 'General', 'action' => 'help', 'scope' => 'global', 'when' => 'always'],
        ['id' => 'command-company', 'keys' => 'K', 'label' => 'Company', 'group' => 'Top bar', 'action' => 'focus-company', 'scope' => 'global', 'when' => 'typing-safe'],
        ['id' => 'command-data', 'keys' => 'Y', 'label' => 'Data', 'group' => 'Top bar', 'action' => 'focus-year', 'scope' => 'global', 'when' => 'typing-safe'],
        ['id' => 'command-exchange', 'keys' => 'Z', 'label' => 'Exchange', 'group' => 'Top bar', 'action' => 'navigate', 'scope' => 'global', 'when' => 'typing-safe', 'route' => 'utilities.import'],
        ['id' => 'command-goto', 'keys' => 'G', 'label' => 'Go To', 'group' => 'Top bar', 'action' => 'goto', 'scope' => 'global', 'when' => 'typing-safe'],
        ['id' => 'command-import', 'keys' => 'O', 'label' => 'Import', 'group' => 'Top bar', 'action' => 'navigate', 'scope' => 'global', 'when' => 'typing-safe', 'route' => 'utilities.import'],
        ['id' => 'command-export', 'keys' => 'E', 'label' => 'Export', 'group' => 'Top bar', 'action' => 'navigate', 'scope' => 'global', 'when' => 'typing-safe', 'route' => 'utilities.export'],
        ['id' => 'command-share', 'keys' => 'M', 'label' => 'Share', 'group' => 'Top bar', 'action' => 'share', 'scope' => 'global', 'when' => 'typing-safe'],
        ['id' => 'close', 'keys' => 'Esc', 'label' => 'Go back or close the current panel', 'group' => 'General', 'action' => 'close', 'scope' => 'global', 'when' => 'always'],
        ['id' => 'quit', 'keys' => 'Q', 'label' => 'Quit', 'group' => 'Commands', 'action' => 'close', 'scope' => 'global', 'when' => 'typing-safe'],
        ['id' => 'sidebar', 'keys' => 'Alt+Shift+M', 'label' => 'Show or hide the menu', 'group' => 'General', 'action' => 'sidebar', 'scope' => 'global', 'when' => 'always'],
        ['id' => 'enter', 'keys' => 'Enter', 'label' => 'Accept the field or open the selected row', 'group' => 'Data entry', 'action' => 'enter', 'scope' => 'form', 'when' => 'field'],
        ['id' => 'tab', 'keys' => 'Tab', 'label' => 'Next field', 'group' => 'Data entry', 'action' => 'next', 'scope' => 'form', 'when' => 'always', 'intercept' => false],
        ['id' => 'shift-tab', 'keys' => 'Shift+Tab', 'label' => 'Previous field', 'group' => 'Data entry', 'action' => 'previous', 'scope' => 'form', 'when' => 'always', 'intercept' => false],
        ['id' => 'arrow-up', 'keys' => 'ArrowUp', 'label' => 'Previous row or option', 'group' => 'Lists', 'action' => 'move-up', 'scope' => 'list', 'when' => 'list'],
        ['id' => 'arrow-down', 'keys' => 'ArrowDown', 'label' => 'Next row or option', 'group' => 'Lists', 'action' => 'move-down', 'scope' => 'list', 'when' => 'list'],
        ['id' => 'arrow-left', 'keys' => 'ArrowLeft', 'label' => 'Previous option', 'group' => 'Lists', 'action' => 'move-up', 'scope' => 'list', 'when' => 'list'],
        ['id' => 'arrow-right', 'keys' => 'ArrowRight', 'label' => 'Next option', 'group' => 'Lists', 'action' => 'move-down', 'scope' => 'list', 'when' => 'list'],
        ['id' => 'home', 'keys' => 'Home', 'label' => 'First row or option', 'group' => 'Lists', 'action' => 'home', 'scope' => 'list', 'when' => 'list'],
        ['id' => 'end', 'keys' => 'End', 'label' => 'Last row or option', 'group' => 'Lists', 'action' => 'end', 'scope' => 'list', 'when' => 'list'],
        ['id' => 'page-up', 'keys' => 'PageUp', 'label' => 'Page up in the current list', 'group' => 'Lists', 'action' => 'page-up', 'scope' => 'list', 'when' => 'list'],
        ['id' => 'page-down', 'keys' => 'PageDown', 'label' => 'Page down in the current list', 'group' => 'Lists', 'action' => 'page-down', 'scope' => 'list', 'when' => 'list'],
        ['id' => 'drill', 'keys' => 'Ctrl+Enter', 'label' => 'Open the selected record', 'group' => 'Lists', 'action' => 'drill', 'scope' => 'list', 'when' => 'typing-safe'],
        ['id' => 'focus-company', 'keys' => 'F3', 'label' => 'Open the company selector', 'group' => 'Working context', 'action' => 'focus-company', 'scope' => 'global', 'when' => 'always'],
        ['id' => 'focus-branch', 'keys' => 'Alt+Shift+B', 'label' => 'Open the branch selector', 'group' => 'Working context', 'action' => 'focus-branch', 'scope' => 'global', 'when' => 'always'],
        ['id' => 'focus-year', 'keys' => 'Alt+Shift+Y', 'label' => 'Open the financial year selector', 'group' => 'Working context', 'action' => 'focus-year', 'scope' => 'global', 'when' => 'always'],
        ['id' => 'go-dashboard', 'keys' => 'Alt+Shift+D', 'label' => 'Dashboard', 'group' => 'Go to', 'action' => 'navigate', 'scope' => 'global', 'when' => 'always', 'route' => 'dashboard'],
        ['id' => 'go-companies', 'keys' => 'Alt+Shift+O', 'label' => 'Companies', 'group' => 'Go to', 'action' => 'navigate', 'scope' => 'global', 'when' => 'always', 'route' => 'companies.index'],
        ['id' => 'date', 'keys' => 'F2', 'label' => 'Change Date', 'group' => 'Vouchers', 'action' => 'date', 'scope' => 'global', 'when' => 'always'],
        ['id' => 'post-dated', 'keys' => 'L', 'label' => 'Post-Dated', 'group' => 'Vouchers', 'action' => 'post-dated', 'scope' => 'voucher', 'when' => 'typing-safe'],
        ['id' => 'optional-voucher', 'keys' => 'Ctrl+L', 'label' => 'Optional', 'group' => 'Vouchers', 'action' => 'optional', 'scope' => 'voucher', 'when' => 'always'],
        ['id' => 'period', 'keys' => 'Alt+F2', 'label' => 'Change Period', 'group' => 'Vouchers', 'action' => 'period', 'scope' => 'global', 'when' => 'always'],
        ['id' => 'contra', 'keys' => 'F4', 'label' => 'Contra', 'group' => 'Vouchers', 'action' => 'navigate', 'scope' => 'global', 'when' => 'always', 'route' => 'vouchers.contra.create'],
        ['id' => 'payment', 'keys' => 'F5', 'label' => 'Payment', 'group' => 'Vouchers', 'action' => 'navigate', 'scope' => 'global', 'when' => 'always', 'route' => 'vouchers.payment.create'],
        ['id' => 'receipt', 'keys' => 'F6', 'label' => 'Receipt', 'group' => 'Vouchers', 'action' => 'navigate', 'scope' => 'global', 'when' => 'always', 'route' => 'vouchers.receipt.create'],
        ['id' => 'journal', 'keys' => 'F7', 'label' => 'Journal', 'group' => 'Vouchers', 'action' => 'navigate', 'scope' => 'global', 'when' => 'always', 'route' => 'vouchers.journal.create'],
        ['id' => 'sales', 'keys' => 'F8', 'label' => 'Sales', 'group' => 'Vouchers', 'action' => 'navigate', 'scope' => 'global', 'when' => 'always', 'route' => 'invoices.sales.create'],
        ['id' => 'purchase', 'keys' => 'F9', 'label' => 'Purchase', 'group' => 'Vouchers', 'action' => 'navigate', 'scope' => 'global', 'when' => 'always', 'route' => 'invoices.purchase.create'],
        ['id' => 'credit-note', 'keys' => 'Ctrl+F8', 'label' => 'Credit note', 'group' => 'Vouchers', 'action' => 'navigate', 'scope' => 'global', 'when' => 'always', 'route' => 'invoices.credit-note.create'],
        ['id' => 'debit-note', 'keys' => 'Ctrl+F9', 'label' => 'Debit note', 'group' => 'Vouchers', 'action' => 'navigate', 'scope' => 'global', 'when' => 'always', 'route' => 'invoices.debit-note.create'],
        ['id' => 'stock-journal', 'keys' => 'Alt+F7', 'label' => 'Stock journal', 'description' => 'Opens the stock journal screen.', 'group' => 'Vouchers', 'action' => 'navigate', 'scope' => 'global', 'when' => 'always', 'route' => 'stock.adjustment.create'],
        ['id' => 'stat-payment', 'keys' => 'Alt+F5', 'label' => 'Stat payment', 'group' => 'Vouchers', 'action' => 'navigate', 'scope' => 'global', 'when' => 'always', 'route' => 'vouchers.payment.create', 'route_params' => ['stat' => 1]],
        ['id' => 'memo-voucher', 'keys' => 'Ctrl+F7', 'label' => 'Memorandum', 'group' => 'Vouchers', 'action' => 'navigate', 'scope' => 'global', 'when' => 'always', 'route' => 'vouchers.journal.create', 'route_params' => ['memo' => 1]],
        ['id' => 'reversing-journal', 'keys' => 'Alt+F6', 'label' => 'Reversing journal', 'group' => 'Vouchers', 'action' => 'navigate', 'scope' => 'global', 'when' => 'always', 'route' => 'vouchers.journal.create', 'route_params' => ['reversing' => 1]],
        ['id' => 'voucher-class', 'keys' => 'Alt+F11', 'label' => 'Voucher class', 'group' => 'Vouchers', 'action' => 'navigate', 'scope' => 'global', 'when' => 'always', 'route' => 'vouchers.classes.index'],
        ['id' => 'filter', 'keys' => 'Ctrl+F', 'label' => 'Search or filter the current screen', 'group' => 'Commands', 'action' => 'filter', 'scope' => 'list', 'when' => 'typing-safe'],
        ['id' => 'accept', 'keys' => 'Ctrl+A', 'label' => 'Save or accept', 'group' => 'Commands', 'action' => 'accept', 'scope' => 'form', 'when' => 'typing-safe'],
        ['id' => 'accept-key', 'keys' => 'A', 'label' => 'Accept', 'group' => 'Commands', 'action' => 'accept', 'scope' => 'form', 'when' => 'typing-safe'],
        ['id' => 'delete', 'keys' => 'Alt+D', 'label' => 'Delete or remove the selected record', 'group' => 'Commands', 'action' => 'delete', 'scope' => 'global', 'when' => 'always'],
        ['id' => 'delete-key', 'keys' => 'D', 'label' => 'Delete', 'group' => 'Commands', 'action' => 'delete', 'scope' => 'global', 'when' => 'typing-safe'],
        ['id' => 'toggle-active', 'keys' => 'Alt+Shift+A', 'label' => 'Deactivate or activate the selected record', 'group' => 'Commands', 'action' => 'toggle-active', 'scope' => 'list', 'when' => 'list'],
        ['id' => 'cancel', 'keys' => 'Alt+X', 'label' => 'Cancel and go back', 'group' => 'Commands', 'action' => 'cancel', 'scope' => 'global', 'when' => 'always'],
        ['id' => 'cancel-key', 'keys' => 'X', 'label' => 'Cancel voucher', 'group' => 'Commands', 'action' => 'cancel', 'scope' => 'global', 'when' => 'typing-safe'],
        ['id' => 'print', 'keys' => 'P', 'label' => 'Print the current document', 'group' => 'Commands', 'action' => 'print', 'scope' => 'global', 'when' => 'typing-safe'],
        ['id' => 'remove-line', 'keys' => 'Ctrl+D', 'label' => 'Remove the current voucher or item line', 'group' => 'Commands', 'action' => 'remove-line', 'scope' => 'voucher', 'when' => 'line'],
        ['id' => 'create', 'keys' => 'Alt+C', 'label' => 'Create a master', 'group' => 'Commands', 'action' => 'create', 'scope' => 'global', 'when' => 'always'],
        ['id' => 'calculator', 'keys' => 'Ctrl+N', 'label' => 'Calculator', 'group' => 'Commands', 'action' => 'calculator', 'scope' => 'global', 'when' => 'typing-safe'],
        ['id' => 'list', 'keys' => 'F10', 'label' => 'Other vouchers, masters, or reports', 'group' => 'Commands', 'action' => 'context-f10', 'scope' => 'global', 'when' => 'always', 'route' => 'vouchers.other'],
        ['id' => 'company-features', 'keys' => 'F11', 'label' => 'Company features', 'group' => 'Commands', 'action' => 'navigate', 'scope' => 'global', 'when' => 'always', 'route' => 'companies.features'],
        ['id' => 'configuration', 'keys' => 'F12', 'label' => 'Voucher and report configuration', 'group' => 'Commands', 'action' => 'navigate', 'scope' => 'global', 'when' => 'always', 'route' => 'preferences.edit'],
        ['id' => 'keyboard-settings', 'keys' => 'Ctrl+Alt+K', 'label' => 'Keyboard shortcut settings', 'group' => 'Commands', 'action' => 'navigate', 'scope' => 'global', 'when' => 'always', 'route' => 'settings.shortcuts'],
        ['id' => 'nav-masters', 'keys' => 'Alt+Shift+G', 'label' => 'Open the Masters menu', 'group' => 'Go to', 'action' => 'open-section', 'scope' => 'navigation', 'when' => 'always', 'section' => 'masters'],
        ['id' => 'nav-transactions', 'keys' => 'Alt+Shift+T', 'label' => 'Open the Transactions menu', 'group' => 'Go to', 'action' => 'open-section', 'scope' => 'navigation', 'when' => 'always', 'section' => 'transactions'],
        ['id' => 'nav-reports', 'keys' => 'Alt+Shift+R', 'label' => 'Open the Reports menu', 'group' => 'Go to', 'action' => 'open-section', 'scope' => 'navigation', 'when' => 'always', 'section' => 'reports'],
        ['id' => 'nav-utilities', 'keys' => 'Alt+Shift+U', 'label' => 'Open the Utilities menu', 'group' => 'Go to', 'action' => 'open-section', 'scope' => 'navigation', 'when' => 'always', 'section' => 'utilities'],
        ['id' => 'nav-settings', 'keys' => 'Alt+Shift+S', 'label' => 'Open the Settings menu', 'group' => 'Go to', 'action' => 'open-section', 'scope' => 'navigation', 'when' => 'always', 'section' => 'settings'],
        ['id' => 'go-groups', 'keys' => 'Alt+Shift+H', 'label' => 'Account groups', 'group' => 'Go to', 'action' => 'navigate', 'scope' => 'navigation', 'when' => 'always', 'route' => 'account-groups.index'],
        ['id' => 'go-ledgers', 'keys' => 'Alt+Shift+L', 'label' => 'Ledgers', 'group' => 'Go to', 'action' => 'navigate', 'scope' => 'navigation', 'when' => 'always', 'route' => 'ledgers.index'],
        ['id' => 'go-products', 'keys' => 'Alt+Shift+P', 'label' => 'Products', 'group' => 'Go to', 'action' => 'navigate', 'scope' => 'navigation', 'when' => 'always', 'route' => 'products.index'],
        ['id' => 'go-sales-list', 'keys' => 'Alt+Shift+I', 'label' => 'Sales list', 'group' => 'Go to', 'action' => 'navigate', 'scope' => 'navigation', 'when' => 'always', 'route' => 'invoices.sales.index'],
        ['id' => 'go-purchase-list', 'keys' => 'Alt+Shift+W', 'label' => 'Purchase list', 'group' => 'Go to', 'action' => 'navigate', 'scope' => 'navigation', 'when' => 'always', 'route' => 'invoices.purchase.index'],
        ['id' => 'go-stock-movements', 'keys' => 'Alt+Shift+V', 'label' => 'Stock movements', 'group' => 'Go to', 'action' => 'navigate', 'scope' => 'navigation', 'when' => 'always', 'route' => 'stock-movements.index'],
        ['id' => 'go-journal-list', 'keys' => 'Alt+Shift+J', 'label' => 'Journal list', 'group' => 'Go to', 'action' => 'navigate', 'scope' => 'navigation', 'when' => 'always', 'route' => 'vouchers.index', 'route_params' => ['voucher_type' => 'journal']],
        ['id' => 'go-payment-list', 'keys' => 'Alt+Shift+K', 'label' => 'Payment list', 'group' => 'Go to', 'action' => 'navigate', 'scope' => 'navigation', 'when' => 'always', 'route' => 'vouchers.index', 'route_params' => ['voucher_type' => 'payment']],
        ['id' => 'go-receipt-list', 'keys' => 'Alt+Shift+E', 'label' => 'Receipt list', 'group' => 'Go to', 'action' => 'navigate', 'scope' => 'navigation', 'when' => 'always', 'route' => 'vouchers.index', 'route_params' => ['voucher_type' => 'receipt']],
        ['id' => 'go-contra-list', 'keys' => 'Alt+Shift+Q', 'label' => 'Contra list', 'group' => 'Go to', 'action' => 'navigate', 'scope' => 'navigation', 'when' => 'always', 'route' => 'vouchers.index', 'route_params' => ['voucher_type' => 'contra']],
        ['id' => 'select-row', 'keys' => 'Space', 'label' => 'Select the current row', 'group' => 'Lists', 'action' => 'select-row', 'scope' => 'list', 'when' => 'list'],
        ['id' => 'select-range', 'keys' => 'Shift+Space', 'label' => 'Extend the row selection', 'group' => 'Lists', 'action' => 'select-range', 'scope' => 'list', 'when' => 'list'],
        ['id' => 'copy-rows', 'keys' => 'Ctrl+C', 'label' => 'Copy the selected rows', 'group' => 'Lists', 'action' => 'copy', 'scope' => 'list', 'when' => 'typing-safe'],
        ['id' => 'duplicate-line', 'keys' => 'Alt+Shift+N', 'label' => 'Duplicate the current line', 'group' => 'Vouchers', 'action' => 'duplicate-line', 'scope' => 'voucher', 'when' => 'line'],
        ['id' => 'record-previous', 'keys' => 'Alt+PageUp', 'label' => 'Previous record', 'group' => 'Lists', 'action' => 'record-previous', 'scope' => 'list', 'when' => 'list'],
        ['id' => 'record-next', 'keys' => 'Alt+PageDown', 'label' => 'Next record', 'group' => 'Lists', 'action' => 'record-next', 'scope' => 'list', 'when' => 'list'],
        ['id' => 'go-boms', 'keys' => 'Alt+Shift+Z', 'label' => 'Bills of materials', 'group' => 'Go to', 'action' => 'navigate', 'scope' => 'navigation', 'when' => 'always', 'route' => 'boms.index'],
        ['id' => 'go-manufacturing', 'keys' => 'Alt+Shift+F', 'label' => 'Manufacturing', 'group' => 'Go to', 'action' => 'navigate', 'scope' => 'navigation', 'when' => 'always', 'route' => 'manufacturing.index'],
        ['id' => 'go-audit', 'keys' => 'Alt+Shift+X', 'label' => 'Audit trail', 'group' => 'Go to', 'action' => 'navigate', 'scope' => 'navigation', 'when' => 'always', 'route' => 'audit.index'],
        ['id' => 'go-parties', 'keys' => 'Ctrl+Alt+P', 'label' => 'Parties', 'group' => 'Go to', 'action' => 'navigate', 'scope' => 'navigation', 'when' => 'always', 'route' => 'parties.index'],
        ['id' => 'go-users', 'keys' => 'Ctrl+Alt+U', 'label' => 'Users', 'group' => 'Go to', 'action' => 'navigate', 'scope' => 'navigation', 'when' => 'always', 'route' => 'users.index'],
        ['id' => 'go-roles', 'keys' => 'Ctrl+Alt+R', 'label' => 'Roles', 'group' => 'Go to', 'action' => 'navigate', 'scope' => 'navigation', 'when' => 'always', 'route' => 'roles.index'],
        ['id' => 'go-preferences', 'keys' => 'Ctrl+Alt+F', 'label' => 'Preferences', 'group' => 'Go to', 'action' => 'navigate', 'scope' => 'navigation', 'when' => 'always', 'route' => 'preferences.edit'],
    ],
];
