<?php

return [
    'sections' => [
        [
            'key' => 'dashboard',
            'label' => 'Dashboard',
            'route' => 'dashboard',
            'active' => ['dashboard'],
            'shortcut' => 'go-dashboard',
        ],
        [
            'key' => 'masters',
            'label' => 'Masters',
            'shortcut' => 'nav-masters',
            'children' => [
                [
                    'key' => 'groups',
                    'label' => 'Groups',
                    'shortcut' => 'go-groups',
                    'route' => 'account-groups.index',
                    'active' => ['account-groups.*'],
                    'domain' => 'accounting',
                    'keywords' => 'account groups',
                ],
                [
                    'key' => 'ledgers',
                    'label' => 'Ledgers',
                    'shortcut' => 'go-ledgers',
                    'route' => 'ledgers.index',
                    'active' => ['ledgers.*'],
                    'domain' => 'accounting',
                    'keywords' => 'accounts',
                ],
                ['key' => 'parties', 'label' => 'Parties', 'shortcut' => 'go-parties', 'route' => 'parties.index', 'active' => ['parties.*'], 'domain' => 'accounting', 'keywords' => 'customers suppliers'],
                ['key' => 'units', 'label' => 'Units', 'route' => 'units.index', 'active' => ['units.*'], 'domain' => 'inventory', 'keywords' => 'uom measurement'],
                ['key' => 'hsn-sac', 'label' => 'HSN / SAC', 'route' => 'hsn-sacs.index', 'active' => ['hsn-sacs.*'], 'domain' => 'tax', 'keywords' => 'hsn sac'],
                ['key' => 'product-groups', 'label' => 'Product Groups', 'route' => 'product-groups.index', 'active' => ['product-groups.*'], 'domain' => 'inventory', 'keywords' => 'stock groups'],
                ['key' => 'products', 'label' => 'Products', 'shortcut' => 'go-products', 'route' => 'products.index', 'active' => ['products.*'], 'domain' => 'inventory', 'keywords' => 'stock items sku'],
                ['key' => 'price-lists', 'label' => 'Price Lists', 'route' => 'price-lists.index', 'active' => ['price-lists.*'], 'domain' => 'inventory', 'keywords' => 'price list price level'],
                ['key' => 'godowns', 'label' => 'Godowns', 'route' => 'godowns.index', 'active' => ['godowns.*'], 'domain' => 'inventory', 'keywords' => 'warehouses locations'],
                ['key' => 'boms', 'label' => 'Bills of Materials', 'shortcut' => 'go-boms', 'route' => 'boms.index', 'active' => ['boms.*'], 'domain' => 'inventory', 'keywords' => 'bom manufacturing recipe'],
                ['key' => 'tax-categories', 'label' => 'Tax Categories', 'route' => 'tax-categories.index', 'active' => ['tax-categories.*'], 'domain' => 'tax', 'keywords' => 'gst tax category'],
                ['key' => 'tax-rates', 'label' => 'Tax Rates', 'route' => 'tax-rates.index', 'active' => ['tax-rates.*'], 'domain' => 'tax', 'keywords' => 'cgst sgst igst cess'],
                ['key' => 'tax-accounts', 'label' => 'Tax Accounts', 'route' => 'tax-accounts.index', 'active' => ['tax-accounts.*'], 'domain' => 'tax', 'keywords' => 'gst ledger cgst sgst igst cess'],
                ['key' => 'currencies', 'label' => 'Currencies', 'route' => 'currencies.index', 'active' => ['currencies.*'], 'domain' => 'accounting', 'keywords' => 'currency exchange'],
                ['key' => 'voucher-types', 'label' => 'Voucher Types', 'route' => 'voucher-types.index', 'active' => ['voucher-types.*'], 'domain' => 'accounting', 'keywords' => 'voucher type numbering'],
                ['key' => 'gst-registrations', 'label' => 'GST Registrations', 'route' => 'gst-registrations.index', 'active' => ['gst-registrations.*'], 'domain' => 'tax', 'keywords' => 'gstin registration'],
                ['key' => 'merchant-profiles', 'label' => 'Merchant Profiles', 'route' => 'merchant-profiles.index', 'active' => ['merchant-profiles.*'], 'domain' => 'accounting', 'keywords' => 'merchant payment'],
                ['key' => 'employees', 'label' => 'Employees', 'route' => 'employees.index', 'active' => ['employees.*'], 'domain' => 'accounting', 'keywords' => 'payroll employee'],
                ['key' => 'pay-heads', 'label' => 'Pay Heads', 'route' => 'pay-heads.index', 'active' => ['pay-heads.*'], 'domain' => 'accounting', 'keywords' => 'payroll pay head'],
                ['key' => 'cost-categories', 'label' => 'Cost Categories', 'route' => 'cost-categories.index', 'active' => ['cost-categories.*'], 'domain' => 'accounting', 'keywords' => 'cost category'],
                ['key' => 'cost-centres', 'label' => 'Cost Centres', 'route' => 'cost-centres.index', 'active' => ['cost-centres.*'], 'domain' => 'accounting', 'keywords' => 'cost centre center'],
                ['key' => 'budgets', 'label' => 'Budgets', 'route' => 'budgets.index', 'active' => ['budgets.*'], 'domain' => 'accounting', 'keywords' => 'budget'],
                ['key' => 'deduction-sections', 'label' => 'TDS / TCS', 'route' => 'deduction-sections.index', 'active' => ['deduction-sections.*'], 'domain' => 'tax', 'keywords' => 'tds tcs deduction'],
            ],
        ],
        [
            'key' => 'transactions',
            'label' => 'Transactions',
            'shortcut' => 'nav-transactions',
            'children' => [
                ['key' => 'sales', 'label' => 'Sales', 'shortcut' => 'go-sales-list', 'route' => 'invoices.sales.index', 'active' => ['invoices.sales.*'], 'domain' => 'sales', 'keywords' => 'sales invoice customer'],
                ['key' => 'credit-note', 'label' => 'Credit Note', 'shortcut' => 'credit-note', 'route' => 'invoices.credit-note.index', 'active' => ['invoices.credit-note.*'], 'domain' => 'sales', 'keywords' => 'credit note sales return'],
                ['key' => 'purchase', 'label' => 'Purchase', 'shortcut' => 'go-purchase-list', 'route' => 'invoices.purchase.index', 'active' => ['invoices.purchase.*'], 'domain' => 'purchase', 'keywords' => 'purchase invoice supplier'],
                ['key' => 'debit-note', 'label' => 'Debit Note', 'shortcut' => 'debit-note', 'route' => 'invoices.debit-note.index', 'active' => ['invoices.debit-note.*'], 'domain' => 'purchase', 'keywords' => 'debit note purchase return'],
                ['key' => 'purchase-orders', 'label' => 'Purchase Orders (not posted)', 'route' => 'purchase-orders.index', 'active' => ['purchase-orders.*'], 'domain' => 'purchase', 'keywords' => 'purchase order po no stock'],
                ['key' => 'sales-orders', 'label' => 'Sales Orders', 'route' => 'sales-orders.index', 'active' => ['sales-orders.*'], 'domain' => 'sales', 'keywords' => 'sales order customer'],
                ['key' => 'payment-requests', 'label' => 'Payment Requests', 'route' => 'payment-requests.index', 'active' => ['payment-requests.*'], 'domain' => 'accounting', 'keywords' => 'payment request'],
                ['key' => 'payroll', 'label' => 'Payroll', 'route' => 'payroll.index', 'active' => ['payroll.index', 'payroll.show', 'payroll.create', 'payroll.store', 'payroll.process', 'payroll.destroy'], 'domain' => 'accounting', 'keywords' => 'salary payroll'],
                ['key' => 'attendance', 'label' => 'Attendance', 'route' => 'payroll.attendance', 'active' => ['payroll.attendance', 'payroll.attendance.store'], 'domain' => 'accounting', 'keywords' => 'attendance leave'],
                ['key' => 'stock-in', 'label' => 'Receipt Note', 'route' => 'stock.in.index', 'active' => ['stock.in.*'], 'domain' => 'inventory', 'keywords' => 'stock inward receipt note'],
                ['key' => 'stock-out', 'label' => 'Delivery Note', 'route' => 'stock.out.index', 'active' => ['stock.out.*'], 'domain' => 'inventory', 'keywords' => 'stock outward delivery note'],
                ['key' => 'stock-transfer', 'label' => 'Stock Transfer', 'route' => 'stock.transfer.index', 'active' => ['stock.transfer.*'], 'domain' => 'inventory', 'keywords' => 'godown transfer'],
                ['key' => 'stock-adjustment', 'label' => 'Stock Journal', 'route' => 'stock.adjustment.index', 'active' => ['stock.adjustment.*'], 'domain' => 'inventory', 'keywords' => 'stock journal adjustment'],
                ['key' => 'manufacturing', 'label' => 'Manufacturing', 'shortcut' => 'go-manufacturing', 'route' => 'manufacturing.index', 'active' => ['manufacturing.*'], 'domain' => 'inventory', 'keywords' => 'production bom journal'],
                ['key' => 'stock-movements', 'label' => 'Stock Movement List', 'shortcut' => 'go-stock-movements', 'route' => 'stock-movements.index', 'active' => ['stock-movements.*'], 'domain' => 'inventory', 'keywords' => 'stock history movement list'],
                ['key' => 'receipt', 'label' => 'Receipt', 'shortcut' => 'go-receipt-list', 'route' => 'vouchers.index', 'params' => ['voucher_type' => 'receipt'], 'voucher' => 'receipt', 'domain' => 'accounting', 'keywords' => 'receipt cash bank'],
                ['key' => 'payment', 'label' => 'Payment', 'shortcut' => 'go-payment-list', 'route' => 'vouchers.index', 'params' => ['voucher_type' => 'payment'], 'voucher' => 'payment', 'domain' => 'accounting', 'keywords' => 'payment cash bank'],
                ['key' => 'contra', 'label' => 'Contra', 'shortcut' => 'go-contra-list', 'route' => 'vouchers.index', 'params' => ['voucher_type' => 'contra'], 'voucher' => 'contra', 'domain' => 'accounting', 'keywords' => 'contra cash bank transfer'],
                ['key' => 'journal', 'label' => 'Journal', 'shortcut' => 'go-journal-list', 'route' => 'vouchers.index', 'params' => ['voucher_type' => 'journal'], 'voucher' => 'journal', 'domain' => 'accounting', 'keywords' => 'journal voucher'],
            ],
        ],
        [
            'key' => 'banking',
            'label' => 'Banking',
            'children' => [
                ['key' => 'bank-accounts', 'label' => 'Bank Accounts', 'route' => 'banking.accounts', 'active' => ['banking.accounts'], 'domain' => 'accounting', 'keywords' => 'bank account ifsc'],
                ['key' => 'bank-transactions', 'label' => 'Bank Transactions', 'route' => 'banking.transactions', 'active' => ['banking.transactions'], 'domain' => 'accounting', 'keywords' => 'bank book'],
                ['key' => 'bank-reconciliation', 'label' => 'Bank Reconciliation', 'route' => 'banking.reconciliation', 'active' => ['banking.reconciliation'], 'domain' => 'accounting', 'keywords' => 'reconcile bank'],
                ['key' => 'bank-statements', 'label' => 'Bank Statement Import', 'route' => 'bank-statements.index', 'active' => ['bank-statements.*'], 'domain' => 'accounting', 'keywords' => 'bank statement csv import'],
            ],
        ],
        [
            'key' => 'reports',
            'label' => 'Reports',
            'shortcut' => 'nav-reports',
            'children' => [
                ['key' => 'day-book', 'label' => 'Day Book', 'route' => 'reports.day-book', 'active' => ['reports.day-book'], 'domain' => 'reporting', 'keywords' => 'daybook'],
                ['key' => 'ledger-report', 'label' => 'Ledger', 'route' => 'reports.ledger', 'active' => ['reports.ledger'], 'domain' => 'reporting'],
                ['key' => 'trial-balance', 'label' => 'Trial Balance', 'route' => 'reports.trial-balance', 'active' => ['reports.trial-balance'], 'domain' => 'reporting', 'keywords' => 'tb'],
                ['key' => 'profit-and-loss', 'label' => 'Profit & Loss', 'route' => 'reports.profit-and-loss', 'active' => ['reports.profit-and-loss'], 'domain' => 'reporting', 'keywords' => 'p&l profit loss'],
                ['key' => 'balance-sheet', 'label' => 'Balance Sheet', 'route' => 'reports.balance-sheet', 'active' => ['reports.balance-sheet'], 'domain' => 'reporting'],
                ['key' => 'stock-summary', 'label' => 'Stock Summary', 'route' => 'reports.stock-summary', 'active' => ['reports.stock-summary'], 'domain' => 'inventory', 'keywords' => 'stock'],
                ['key' => 'ratio-analysis', 'label' => 'Ratio Analysis', 'route' => 'reports.ratio-analysis', 'active' => ['reports.ratio-analysis'], 'domain' => 'reporting', 'keywords' => 'ratios'],
                ['key' => 'stock-ledger', 'label' => 'Stock Ledger', 'route' => 'reports.stock-ledger', 'active' => ['reports.stock-ledger'], 'domain' => 'inventory', 'keywords' => 'stock ledger'],
                ['key' => 'godown-stock', 'label' => 'Godown-wise Stock', 'route' => 'reports.godown-stock', 'active' => ['reports.godown-stock'], 'domain' => 'inventory', 'keywords' => 'godown stock'],
                ['key' => 'stock-movement-report', 'label' => 'Stock Movement Report', 'route' => 'reports.stock-movements', 'active' => ['reports.stock-movements'], 'domain' => 'inventory', 'keywords' => 'stock movement report'],
                ['key' => 'low-stock', 'label' => 'Low Stock', 'route' => 'reports.low-stock', 'active' => ['reports.low-stock'], 'domain' => 'inventory', 'keywords' => 'reorder minimum'],
                ['key' => 'stock-valuation', 'label' => 'Stock Valuation', 'route' => 'reports.stock-valuation', 'active' => ['reports.stock-valuation'], 'domain' => 'inventory', 'keywords' => 'valuation stock value'],
                ['key' => 'expiry', 'label' => 'Expiry', 'route' => 'reports.expiry', 'active' => ['reports.expiry'], 'domain' => 'inventory', 'keywords' => 'batch expiry'],
                ['key' => 'stock-limits', 'label' => 'Stock Limits', 'route' => 'reports.stock-limits', 'active' => ['reports.stock-limits'], 'domain' => 'inventory', 'keywords' => 'maximum reorder'],
                ['key' => 'batch-history', 'label' => 'Batch / Serial History', 'route' => 'reports.batch-history', 'active' => ['reports.batch-history'], 'domain' => 'inventory', 'keywords' => 'batch serial history'],
                ['key' => 'production', 'label' => 'Production', 'route' => 'reports.production', 'active' => ['reports.production'], 'domain' => 'inventory', 'keywords' => 'manufacturing production'],
                ['key' => 'consumption', 'label' => 'Consumption', 'route' => 'reports.consumption', 'active' => ['reports.consumption'], 'domain' => 'inventory', 'keywords' => 'raw material consumption'],
                ['key' => 'gst', 'label' => 'GST Summary', 'route' => 'reports.gst', 'active' => ['reports.gst'], 'domain' => 'tax', 'keywords' => 'gst output input hsn'],
                ['key' => 'gstr-1', 'label' => 'GSTR-1', 'route' => 'reports.gstr-1', 'active' => ['reports.gstr-1'], 'domain' => 'tax', 'keywords' => 'gstr1 b2b b2c hsn'],
                ['key' => 'gstr-3b', 'label' => 'GSTR-3B', 'route' => 'reports.gstr-3b', 'active' => ['reports.gstr-3b'], 'domain' => 'tax', 'keywords' => 'gstr3b itc liability'],
                ['key' => 'tds-return', 'label' => 'TDS / TCS', 'route' => 'reports.tds', 'active' => ['reports.tds'], 'domain' => 'tax', 'keywords' => 'tds tcs return'],
                ['key' => 'budget-variance', 'label' => 'Budget Variance', 'route' => 'reports.budget-variance', 'active' => ['reports.budget-variance'], 'domain' => 'reporting', 'keywords' => 'budget variance actual'],
                ['key' => 'cash-flow', 'label' => 'Cash Flow', 'route' => 'reports.cash-flow', 'active' => ['reports.cash-flow'], 'domain' => 'reporting', 'keywords' => 'cash flow operating investing financing'],
                ['key' => 'funds-flow', 'label' => 'Funds Flow', 'route' => 'reports.funds-flow', 'active' => ['reports.funds-flow'], 'domain' => 'reporting', 'keywords' => 'funds flow sources applications'],
                ['key' => 'account-books', 'label' => 'Account Books', 'route' => 'reports.account-books', 'active' => ['reports.account-books'], 'domain' => 'reporting', 'keywords' => 'cash book bank book'],
                ['key' => 'statements-of-accounts', 'label' => 'Statements of Accounts', 'route' => 'reports.statements-of-accounts', 'active' => ['reports.statements-of-accounts'], 'domain' => 'reporting', 'keywords' => 'statement of account'],
                ['key' => 'inventory-books', 'label' => 'Inventory Books', 'route' => 'reports.inventory-books', 'active' => ['reports.inventory-books'], 'domain' => 'inventory', 'keywords' => 'inventory books'],
                ['key' => 'statements-of-inventory', 'label' => 'Statements of Inventory', 'route' => 'reports.statements-of-inventory', 'active' => ['reports.statements-of-inventory'], 'domain' => 'inventory', 'keywords' => 'statement of inventory'],
                ['key' => 'exceptions', 'label' => 'Exception Reports', 'route' => 'reports.exceptions', 'active' => ['reports.exceptions'], 'domain' => 'reporting', 'keywords' => 'exceptions negative stock'],
                ['key' => 'analysis', 'label' => 'Analysis & Verification', 'route' => 'reports.analysis', 'active' => ['reports.analysis'], 'domain' => 'reporting', 'keywords' => 'verification analysis'],
                ['key' => 'edit-log', 'label' => 'Edit Log Summary', 'route' => 'reports.edit-log', 'active' => ['reports.edit-log'], 'domain' => 'reporting', 'keywords' => 'edit log audit summary'],
                ['key' => 'sales-order-report', 'label' => 'Sales Order Report', 'route' => 'sales-orders.report', 'active' => ['sales-orders.report'], 'domain' => 'reporting', 'keywords' => 'sales order report'],
                ['key' => 'payroll-report', 'label' => 'Payroll Report', 'route' => 'payroll.report', 'active' => ['payroll.report'], 'domain' => 'reporting', 'keywords' => 'payroll report'],
                ['key' => 'cost-centre-report', 'label' => 'Cost Centre Report', 'route' => 'reports.cost-centres', 'active' => ['reports.cost-centres'], 'domain' => 'reporting', 'keywords' => 'cost centre'],
                ['key' => 'interest', 'label' => 'Interest', 'route' => 'reports.interest', 'active' => ['reports.interest'], 'domain' => 'reporting', 'keywords' => 'interest overdue'],
                ['key' => 'outstanding', 'label' => 'Outstanding', 'route' => 'reports.outstanding', 'active' => ['reports.outstanding'], 'domain' => 'reporting', 'keywords' => 'receivables payables'],
            ],
        ],
        [
            'key' => 'utilities',
            'label' => 'Utilities',
            'shortcut' => 'nav-utilities',
            'children' => [
                ['key' => 'import', 'label' => 'Import', 'route' => 'utilities.import', 'active' => ['utilities.import', 'utilities.import.template', 'utilities.import.store'], 'domain' => 'integrations', 'keywords' => 'csv excel upload'],
                ['key' => 'export', 'label' => 'Export', 'route' => 'utilities.export', 'active' => ['utilities.export', 'utilities.export.download'], 'domain' => 'integrations', 'keywords' => 'csv excel download'],
                ['key' => 'backup', 'label' => 'Backup', 'route' => 'utilities.backup', 'active' => ['utilities.backup', 'utilities.backup.store', 'utilities.backup.download', 'utilities.backup.restore', 'utilities.backup.restore.store'], 'domain' => 'integrations', 'keywords' => 'restore backup'],
            ],
        ],
        [
            'key' => 'settings',
            'label' => 'Settings',
            'shortcut' => 'nav-settings',
            'children' => [
                [
                    'key' => 'companies',
                    'label' => 'Companies',
                    'shortcut' => 'company-features',
                    'route' => 'companies.index',
                    'active' => ['companies.index', 'companies.create', 'companies.store', 'companies.show', 'companies.edit', 'companies.update', 'companies.activation'],
                    'domain' => 'platform',
                ],
                [
                    'key' => 'branches',
                    'label' => 'Branches',
                    'route' => 'branches.current',
                    'active' => ['branches.current', 'companies.branches.*'],
                    'domain' => 'platform',
                ],
                [
                    'key' => 'financial-years',
                    'label' => 'Financial Years',
                    'route' => 'financial-years.current',
                    'active' => ['financial-years.current', 'companies.financial-years.*'],
                    'domain' => 'platform',
                ],
                [
                    'key' => 'audit',
                    'label' => 'Audit Trail',
                    'shortcut' => 'go-audit',
                    'route' => 'audit.index',
                    'active' => ['audit.index', 'audit.show'],
                    'domain' => 'platform',
                    'keywords' => 'audit log history security',
                ],
                [
                    'key' => 'security-events',
                    'label' => 'Security Events',
                    'route' => 'audit.security',
                    'active' => ['audit.security'],
                    'domain' => 'platform',
                    'keywords' => 'login failed password session',
                ],
                [
                    'key' => 'shortcuts',
                    'label' => 'Keyboard Shortcuts',
                    'shortcut' => 'keyboard-settings',
                    'route' => 'settings.shortcuts',
                    'active' => ['settings.shortcuts', 'settings.shortcuts.update', 'settings.shortcuts.restore', 'settings.shortcuts.restore-all'],
                    'domain' => 'platform',
                    'keywords' => 'keyboard tally shortcuts',
                ],
                ['key' => 'users', 'label' => 'Users', 'shortcut' => 'go-users', 'route' => 'users.index', 'active' => ['users.*'], 'domain' => 'platform'],
                ['key' => 'roles', 'label' => 'Roles & Permissions', 'shortcut' => 'go-roles', 'route' => 'roles.index', 'active' => ['roles.*'], 'domain' => 'platform'],
                ['key' => 'preferences', 'label' => 'Preferences', 'shortcut' => 'configuration', 'route' => 'preferences.edit', 'active' => ['preferences.*'], 'domain' => 'platform'],
            ],
        ],
    ],
];
